name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - uses: ipfs/aegir/actions/cache-node-modules@master

  check:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - uses: ipfs/aegir/actions/cache-node-modules@master
      - run: npm run --if-present lint
      - run: npm run --if-present dep-check

  test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [lts/*]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - uses: ipfs/aegir/actions/cache-node-modules@master
      - run: npm run --if-present test
